// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rrgjlfnebnscjnyyuyef.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJyZ2psZm5lYm5zY2pueXl1eWVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4ODM2MTMsImV4cCI6MjA2NzQ1OTYxM30.F3tI8-ZxGMibyFPbFGFNuTCPYoz8e26CAC98e5ACou4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});